root: true
env:
  node: true
  jest: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
rules:
  "no-constant-condition":
    - "error"
    - checkLoops: false
  "@typescript-eslint/no-non-null-assertion": 0
